### ISSUE TITLE
Switch Font

### ISSUE THREAD

**Issue by brunocalado** [jsavko/swtextcrawl#4]
Hi. 

I'm trying to switch the font. But, I don't know how. Can you help me?

Font: https://aurekfonts.github.io/src/showcase/sienar/sienar.html#

I created a css
```css
@font-face {
	font-family: SienarAFChariot;
	src: url("./fonts/SienarAFChariot.otf") format("opentype");
}
```
```css
  .star-wars {
    display: flex;
    justify-content: center;
    position: relative;
    height: 800px;
    color: #feda4a;
    **font-family: SienarAFChariot, 'Pathway Gothic One', sans-serif;**
    font-size: 500%;
    font-weight: 600;
    letter-spacing: 6px;
    line-height: 150%;
    perspective: 400px;
    text-align: justify;
  }
```
